# Generated by Django 5.2.10 on 2026-01-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='monthly_tokens_used',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
